service: wesoar-api
package:
  excludeDevDependencies: true
  exclude:
    -.env
    -package.lock.json
    -src/**
    -tslint.json
    -tsconfig.json
plugins:
  - serverless-offline

provider:
  name: aws
  stage: api
  runtime: nodejs12.x
  region: ap-south-1

functions:
  graphql:
    handler: ./dist/Handler.graphQlHandler
    events:
      - http: ANY /
      - http: ANY {proxy+}